FROM arm32v7/openjdk

# Note: build has to be performed on the host system.
COPY qemu-arm-static /usr/bin/qemu-arm-static

RUN mkdir argentum-api
WORKDIR argentum-api

RUN apt-get update && apt-get install -y \
  netcat-openbsd

COPY build/libs/argentum-*.jar argentum-api.jar
COPY production/application.yaml .
COPY production/keystore.p12 .
COPY start.sh .

EXPOSE 8443

CMD ["sh", "-e", "start.sh"]