spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/argentum
    username: postgres
    password: ${POSTGRES_PASSWORD}
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate.ddl-auto: update
    generate-ddl: true

  session.store-type: none

server:
  port: 8443
  ssl:
    keyStoreType: PKCS12
    keyAlias: tomcat
    key-store: keystore.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
