version: '3'

# This compose file relies on remote repositories, having no local build files
# available.

services:
  argentum-api:
    image: $API_REMOTE_TAG
    environment:
      - DJANGO_KEY
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=postgres
    ports:
      - '8443:8443'
    depends_on:
      - postgres

  argentum-ui:
    image: $UI_REMOTE_TAG
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - argentum-api

  postgres:
    image: arm32v7/postgres:9
    volumes:
      - ./postgres/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB=argentum
    ports:
      - '5432:5432'
