# Generated by Django 2.1.2 on 2018-10-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('mail', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=32)),
                ('checked_in', models.DateTimeField()),
                ('card', models.CharField(max_length=32)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
