FROM arm32v7/nginx:stable

# Note: build has to be performed on the host system.
COPY qemu-arm-static /usr/bin/qemu-arm-static

COPY production/nginx.conf /etc/nginx/nginx.conf
COPY production/fullchain.pem /
COPY production/privkey.pem /
COPY dist /usr/share/nginx/html
